// Config do Vim
//
// .vimrc

set number
set nohls
set ai

set belloff=all

syntax on
filetype plugin indent on

set ts=4
set sw=4
set expandtab
set noshiftround

set showmode
set showcmd

" bracket remap
inoremap {} {}<Left><Return><Up><End><Return> 

" bracket translator (trocar pra C cedilha)
nnoremap c :g/{/normal kJx<return>
nnoremap C :g/{/normal $xo{<return>
